server:
  port: ${APPLICATION_PORT}

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    password: ${DATABASE_PASSWORD}
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    driver-class-name : com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
